void bolha(int *vetor, int n);
void bolhaComParada(int *vetor, int n);
void insercaoDireta(int *vetor, int n);
void insercaoBinaria(int *vetor, int n);
void shellsort(int *vetor, int n);
void criaHeap(int *vetor, int i, int f);
void heapsort(int *vetor, int n);
void selecaoDireta(int *vetor, int n);
void quicksortIni(int *vetor, int esq, int dir);
void particao(int *vetor, int esquerda, int direita, int *i, int *j);
void ordena(int *vetor, int esquerda, int direita);
void quicksortCentro(int *vetor, int esquerda, int direita);
void intercalar(int *vetor, int inicio, int fim, int meio);
void merge(int *vetor, int inicio, int fim);
void mergesort(int *vetor, int inicio, int fim);
